import pyautogui
import time

time.sleep(5)
pyautogui.moveTo(490, 280)
time.sleep(1)
pyautogui.click(clicks=2, button='left')


time.sleep(2)
pyautogui.moveTo(700, 95)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Minecraft""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Game""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Fortnite""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Forza Horizon""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Coding""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of Computer""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CPU""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of PC""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of UPS""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CD""",interval=0.2)
pyautogui.press('enter')

exit()

time.sleep(5)
pyautogui.moveTo(700, 95)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Minecraft""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is GTA V""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Fortnite""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Forza Horizon""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Coding""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of Computer""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CPU""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of PC""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of UPS""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CD""",interval=0.2)
pyautogui.press('enter')

time.sleep(2)
pyautogui.moveTo(700, 95)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Minecraft""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Game""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Fortnite""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Forza Horizon""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""What is Coding""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of Computer""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CPU""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of PC""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of UPS""",interval=0.2)
pyautogui.press('enter')


time.sleep(3)
pyautogui.click(clicks=1, button='left')
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.press('backspace')
time.sleep(1)
pyautogui.typewrite("""Full Form of CD""",interval=0.2)
pyautogui.press('enter')